main: aliuly\grabbag\Main
api: [1.10.0,1.11.0,1.12.0]
load: POSTWORLD

name: GrabBag
description: Collection of miscellaneous commands and listener modules
version: 2.3.0dev0
author: aliuly
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/GrabBag

permissions:
  gb.cmd.servers:
    default: op
    description: "Allows access to servers command"
  gb.cmd.servers.read:
    default: op
    description: "Allows viewing servers configuration"
  gb.cmd.servers.read.viewip:
    default: op
    description: "Allows viewing servers configuration"
  gb.cmd.servers.read.viewrcon:
    default: op
    description: "Allows viewing servers configuration"
  gb.cmd.servers.write:
    default: op
    description: "Allows changing servers configuration"

#  gb.cmd.permmgr:
#    default: op
#    description: Change permissions
#  gb.cmd.slay:
#    default: op
#    description: "Allow slaying players"
#  gb.cmd.shield:
#    default: op
#    description: "Allow players to become invulnerable"
#  gb.cmd.mute:
#    default: op
#    description: "mute/unmute"
#  gb.cmd.togglechat:
#    default: true
#    description: "lets players opt out from chat"
#  gb.cmd.togglechat.others:
#    default: op
#    description: "lets you toggle chat for others"
#  gb.cmd.togglechat.excempt:
#    default: op
#    description: "chat-off players will always receive chats from these"
#  gb.cmd.togglechat.global:
#    default: op
#    description: "Can toggle chat for the server as a whole"
#  gb.cmd.clearchat:
#    default: true
#    description: "Clear your chat window"
#  gb.cmd.nick:
#    default: true
#    description: "Change display name"
#  gb.cmd.after:
#    default: op
#    description: "Schedule commands"
#  gb.cmd.alias:
#    default: op
#    description: "Allow creating aliases"
#  gb.cmd.sudo:
#    default: op
#    description: "Allow to run command as another user"
#  gb.cmd.burn:
#    default: op
#    description: "Allow the use of burn command"
#  gb.cmd.clearinv:
#    default: true
#    description: "Clear player's inventory"
#  gb.cmd.clearinv.others:
#    default: op
#    description: "Clear other's inventory"
#  gb.cmd.rminv:
#    default: true
#    description: "Remove item from player's inventory"
#  gb.cmd.rminv.others:
#    default: op
#    description: "Remove item from other's inventory"
#  gb.cmd.clearhotbar:
#    default: true
#    description: "Clear player's hotbar"
#  gb.cmd.clearhotbar.others:
#    default: op
#    description: "Clear other's hotbar"
#  gb.cmd.crash:
#    default: op
#    description: "Crash dump management"
#  gb.cmd.entities:
#    default: op
#    description: "Access entities command"
#  gb.cmd.fly:
#    default: op
#    description: "Flight control"
#  gb.cmd.follow:
#    default: op
#    description: "Let players can follow others"
#  gb.cmd.followme:
#    default: op
#    description: "Make players follow you"
#  gb.cmd.freeze:
#    default: op
#    description: "freeze/thaw users"
#  gb.cmd.get:
#    default: op
#    description: "Get blocks"
#  gb.cmd.gma:
#    default: op
#    description: "Allow to switch gamemode to Adventure"
#  gb.cmd.gms:
#    default: op
#    description: "Allow to switch gamemode to survival"
#  gb.cmd.gmc:
#    default: op
#    description: "Allow to switch gamemode to creative"
#  gb.cmd.gmspc:
#    default: op
#    description: "Allow to switch gamemode to spectator"
#  gb.cmd.heal:
#    default: op
#    description: "Allow healing"
#  gb.cmd.invisible:
#    default: op
#    description: make player invisible
#  gb.cmd.invisible.inmune:
#    default: false
#    description: make player inmune to invisibility tricks
#  gb.cmd.opms:
#    default: true
#    description: "Allow to send op only messages"
#  gb.cmd.rpt:
#    default: true
#    description: "Report issues"
#  gb.cmd.rpt.read:
#    default: op
#    description: "Read reported issues"
#  gb.cmd.ops:
#    default: true
#    description: "list server ops"
#  gb.cmd.players:
#    default: true
#    description: "allow players command"
#  gb.cmd.pluginmgr:
#    default: op
#    description: Manage plugins
#  gb.cmd.prefix:
#    default: true
#    description: "Allow the use of /prefix"
#  gb.cmd.rcon:
#    default: op
#    description: "use RCON client"
#  gb.cmd.regs:
#    default: op
#    description: Manage player registrations
#  gb.cmd.reop:
#    default: true
#    description: "Access to reop command"
#  gb.cmd.reop.others:
#    default: op
#    description: "Allows to reop others"
#  gb.cmd.setarmor:
#    default: op
#    description: "Allow you to set your armor"
#  gb.cmd.setarmor.others:
#    default: op
#    description: "Allow you to set others armor"
#  gb.cmd.seearmor:
#    default: op
#    description: "Show player's armor"
#  gb.cmd.seeinv:
#    default: op
#    description: "Show player's inventory"
#  gb.cmd.skin:
#    default: op
#    description: Manage skins
#  gb.cmd.skin.other:
#    default: op
#    description: Manage other's skins skins
#  gb.cmd.spawn:
#    default: true
#    description: "Allow to teleport to spawn"
#  gb.cmd.servicemode:
#    default: op
#    description: "Allow access to service mode command"
#  gb.servicemode.allow:
#    default: op
#    description: "Allow login when in service mode."
#  gb.cmd.summon:
#    default: op
#    description: "Summon|Dismiss command"
#  gb.cmd.throw:
#    default: op
#    description: "Allow to throw players up in the air"
#  gb.cmd.timings:
#    default: op
#    description: "Show timings data"
#  gb.cmd.pushpoptp:
#    default: op
#    description: "push/pop teleport"
#  gb.cmd.whois:
#    default: op
#    description: "Show player details"
#  gb.cmd.whois.showip:
#    default: op
#    description: "Show player IP address"
#  gb.module.cmdsel:
#    default: true
#    description: "Access to command selectors"
#  gb.module.repeater:
#    default: true
#    description: "Access to repeater module"
