main: grabbag\Main
api: 1.10.0
load: POSTWORLD

name: GrabBag
description: Collection of miscellaneous commands and listener modules
version: 1.1.0
author: aliuly

permissions:
    gb.cmd.players:
        default: true
        description: "allow players command"
    gb.cmd.ops:
        default: true
        description: "list server ops"
    gb.cmd.sudo:
        default: op
        description: "Allow to run command as another user"
    gb.cmd.gma:
        default: op
        description: "Allow to switch gamemode to Adventure"
    gb.cmd.gms:
        default: op
        description: "Allow to switch gamemode to survival"
    gb.cmd.gmc:
        default: op
        description: "Allow to switch gamemode to creative"
    gb.cmd.slay:
        default: op
        description: "Allow slaying players"
    gb.cmd.heal:
        default: op
        description: "Allow healing"
    gb.cmd.whois:
        default: op
        description: "Show player details"
    gb.cmd.timings:
        default: op
        description: "Show timings data"
    gb.cmd.seearmor:
        default: op
        description: "Show player's armor"
    gb.cmd.seeinv:
        default: op
        description: "Show player's inventory"
    gb.cmd.get:
        default: op
        description: "Get blocks"
    gb.spawnarmor.receive:
        default: true
        description: "allows to receive armor when you spawn"
    gb.spawnitems.receive:
        default: true
        description: "allows to receive items when you spawn"
    gb.compasstp.allow:
        default: op
        description: "Allow players to use Compass to Teleport"
    gb.cmd.shield:
        default: op
        description: "Allow players to become invulnerable"
