name: SignWarp
api: [1.10.0]
version: 1.3.0
load: POSTWORLD
main: aliuly\signwarp\Main
author: aliuly
softdepend: [ManyWorlds]

permissions:
  signwarp.place.sign:
    default: op
    description: "Allow user to create warp"
  signwarp.touch.sign:
    default: true
    description: "Allow user to use warp"
  signwarp.cmd.xyz:
    default: true
    description: "Shows current x,y,z coordinates"
