name: RunePvP
version: 1.0.0
main: aliuly\runepvp\Main
api: 1.10.0
load: POSTWORLD
depend: [PocketMoney]

description: A funny PvP manager plugin inspired in RuinPvP
author: aliuly

commands:
    runepvp:
        description: Show your RunePvP stats
        usage: "/runepvp"
        aliases: [rp]
        permission: runepvp.cmd

permissions:
    runepvp.cmd:
        default: true
        description: "Give players access to RunePvP command"
#    runepvp.signs.place:
#        default: op
#        description: "Allow users to place RunePvP signs"
#    runepvp.signs.use:
#        default: op
#        description: "Allow users to place RunePvP signs"
