name: RunePvP
version: 1.1.0
main: aliuly\runepvp\Main
api: 1.10.0
load: POSTWORLD
# You have to have at least one of these...
softdepend: [SignShop,PocketMoney,MassiveEconomy,EconomyAPI]

description: A funny PvP manager plugin inspired in RuinPvP
author: aliuly

commands:
    runepvp:
        description: Show your RunePvP stats
        usage: "/runepvp"
        aliases: [rp]
        permission: runepvp.cmd

permissions:
    runepvp.cmd:
        default: true
        description: "Give players access to RunePvP command"
    runepvp.cmd.stats:
        default: true
        description: "Access to stats command"
    runepvp.cmd.stats.other:
        default: op
        description: "View other's stats"
    runepvp.cmd.top:
        default: true
        description: "View top players"

#    runepvp.signs.place:
#        default: op
#        description: "Allow users to place RunePvP signs"
#    runepvp.signs.use:
#        default: op
#        description: "Allow users to place RunePvP signs"
