name: libcommon
version: 1.1.0
main: aliuly\loader\Main
api: 1.12.0
load: STARTUP

description: aliuly's common library
author: aliuly
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/libcommon
