name: libcommon
version: 1.1.1
main: aliuly\loader\Main
api: 1.12.0
load: STARTUP

description: aliuly's common library
author: aliuly
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/libcommon

permissions:
  libcommon.debug.command:
    default: op
    description: "Allow access to libcommon debug commands"
