name: libcommon
version: 1.0.0
main: aliuly\loader\Main
api: 1.10.0
load: POSTWORLD

description: aliuly's common library
author: aliuly
website: https://github.com/alejandroliu/pocketmine-plugins/tree/master/libcommon
