main: ManyWorlds\Main
api: 1.10.0
load: POSTWORLD

name: ManyWorlds
description: Manage Multiple Worlds
version: 1.1.0
author: aliuly

commands:
    mw:
        description: Manage worlds
        usage: "/mw <tp|create|load|unload|ls|motd> <world>"
    motd:
        description: Show a level specific message of the day
        usage: "/motd"

permissions:
    mw.cmd.tp:
        default: op
        description: "Allows users to travel to other worlds"
    mw.cmd.tp:
        default: op
        description: "Allows users to travel to other worlds"
    mw.cmd.tp.others:
        default: op
        description: "Allows users to make others travel to other worlds"
    mw.cmd.world.motd:
        default: op
        description: "Allows users to edit the motd text"
    mw.cmd.world.create:
        default: op
        description: "Allows users to create worlds"
    mw.cmd.world.load:
        default: op
        description: "Allows users to load worlds"
    mw.cmd.world.ls:
        default: op
        description: "Allows users to list worlds"